### ISSUE TITLE
Feat: 공통 TextField 구현

### ISSUE THREAD

**Issue by Sangjun-man** [YAPP-Github/22nd-Web-Team-2-Web#8]
## Description

-  스크린샷 예시
  
  ![image](https://github.com/YAPP-Github/22nd-Web-Team-2-Web/assets/66112027/00df1909-5d24-4655-bdd4-c7b52287bb17)
  ![image](https://github.com/YAPP-Github/22nd-Web-Team-2-Web/assets/66112027/1a9dcc59-e904-4b58-a8e2-214907114831)

  ![image](https://github.com/YAPP-Github/22nd-Web-Team-2-Web/assets/66112027/bbb51e54-868c-4b45-b3d3-922df96a8be5)

  ![image](https://github.com/YAPP-Github/22nd-Web-Team-2-Web/assets/66112027/65de76b4-710e-4413-8b9a-773fec8acc89)

## Todo

- [x] type에 따른 validation 기능 ( 기본 : 전화번호,텍스트 길이, 커스텀 : 보호소 이름 확인)
- [ ] ~~아이콘 추가 기능 (검색 필드에 돋보기모양 아이콘)~~ 
- [x] 내용 전체 삭제기능,
- [x] focus 시 밑줄 애니메이션

## References

- 피그마 디자인을 보며 제작
